### ISSUE TITLE
JEI Log Spam errors... Mod Incompatibility

### ISSUE THREAD

**Issue by Graywaren** [BlakeBr0/MoreBuckets#1]
1.12.2 + F b2805

I installed this mod, cause I really want more buckets! (Though I wish it also included wood and clay ones) However, upon launch I noticed I was getting repeating errors from JEI about failing to get a unique identifier for more bucket items. So many that MultiMC stopped showing it in the log and warned that it might be eating hard drive space.

I tested an instance with just JEI and buckets, and it does not produce this error. I then added liteloader and voxelmap since LL was mentioned in the error... still nothing.... It appears to be some mod incompatibility

 Here's a copy of one such error:

[Client thread/ERROR] [jei]: Failed to get unique identifier for stack.
java.lang.IllegalStateException: Item has no registry name: 1xitem.morebuckets.intermedium_bucket@0 com.blakebr0.morebuckets.item.ItemMoreBucket nbt:{FluidName:"water",Amount:8000}
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:401) ~[StackHelper.class:?]
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:385) ~[StackHelper.class:?]
	at mezz.jei.startup.UniqueItemStackListBuilder.add(UniqueItemStackListBuilder.java:25) ~[UniqueItemStackListBuilder.class:?]
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:379) ~[StackHelper.class:?]
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:360) ~[StackHelper.class:?]
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:345) ~[StackHelper.class:?]
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:328) ~[StackHelper.class:?]
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:322) ~[StackHelper.class:?]
	at mezz.jei.plugins.vanilla.crafting.ShapelessRecipeWrapper.getIngredients(ShapelessRecipeWrapper.java:33) ~[ShapelessRecipeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:285) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:271) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:259) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:231) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:168) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:95) ~[RecipeRegistry.class:?]
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:335) ~[ModRegistry.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77) ~[JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.lambda$loadComplete$0(ProxyCommonClient.java:131) ~[ProxyCommonClient.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.notifyReloadListeners(SimpleReloadableResourceManager.java:132) [cev.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:112) [cev.class:?]
	at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:808) [bib.class:?]
	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45) [ResourcesClient.class:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:275) [LiteLoaderEventBrokerClient.class:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!

Any idea what this might be about or what mod might be causing it? I'll keep trying to pin it down, but since I've got so many it'll take a while and maybe there's something in that error that I don't understand that might give a clue.

**Comment by duely** [comment]
I get the impression that a number of bucket-related items are created but not registered (hence no registry name -- if they were registered it would crash the game because of a null registry name), but somehow JEI is getting ahold of them and attempting to fetch their registry name, which is null. 

Presumably these are bucket types for materials for compat with other mods, but aren't registered because those mods aren't installed.

I'm suffering the same experience myself since the most recent JEI update (that I've noticed).
